name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: "0"
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: install deps
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential git gcc libc-dev libffi-dev bash make apt-utils
      - name: build tools
        run: make tools
      - name: make binary
        run: CGO_ENABLED=0 make package-scanner
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          only-new-issues: true
